config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'orders#index'

  resources :orders, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :orders_products
  has_many :products, through: :orders_products

  def total_tax
    Money.new(TaxCalculatorService.total_tax(self.products))
  end

  def total_cost_with_tax
    Money.new(TaxCalculatorService.total_cost_with_tax(self.products))
  end
end

app/models/orders_product.rb
class OrdersProduct < ApplicationRecord
  belongs_to :order, dependent: :destroy
  belongs_to :product, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :tax_category
  has_many :orders_products
  has_many :orders, through: :orders_products

  monetize :base_price_cents

  def sales_tax_exempt
    return false unless tax_category.present?
    tax_category.sales_tax_exempt
  end

  def sales_tax_exempt?
    sales_tax_exempt
  end

  def price_with_tax
    Money.new(TaxCalculatorService.price_with_tax(self))
  end
end

app/models/tax_category.rb
class TaxCategory < ApplicationRecord
   has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SalesTaxes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <%= yield %>
    </div>
  </body>
</html>

app/views/orders/index.html.erb
<h1>Orders</h1>
<div>Here is a list of Orders in progress. Product prices are listed without tax.</div>

<% @orders.each do |order| %>
	<div class="card">
		<h2>Order #<%= order.identifier %></h2>
		<% order.products.each do |product| %>
			<div><%= product.name %>: <%= humanized_money_with_symbol(product.base_price) %></div>
		<% end %>
		<div class="btn">
			<%= link_to "Show Receipt For Order ##{order.identifier}", order_path(order) %>
		</div>
	</div>
<% end %>

app/views/orders/show.html.erb
<h1>Order #<%= @order.identifier %></h1>
<div>This page displays item prices with tax, and a summary of total tax and total cost with tax for the order.</div>
<div class="card">
	<% @order.products.each do |product| %>
		<div><%= product.name %>: <%= humanized_money_with_symbol(product.price_with_tax) %></div>
	<% end %>
	<div class="card-footer">
		<div>Sales Taxes: <%= humanized_money_with_symbol(@order.total_tax) %></div>
		<div>Total: <%= humanized_money_with_symbol(@order.total_cost_with_tax) %></div>
	</div>
</div>
<div class="btn">
	<%= link_to "Orders Index", orders_path %>
</div>